# dstask.spec
# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/naggie/dstask
%global goipath         github.com/naggie/dstask
Version:                0.26
%gometa -f

%global common_description %{expand:
Git powered terminal-based todo/note manager --  markdown note page per task.
Single binary!}

%global golicenses      LICENSE
%global godocs          doc README.md etc/DATABASE_FORMAT.md etc/FUTURE.md\\\
                        etc/PERFORMANCE.md

Name:           dstask
Release:        %autorelease
Summary:        Git powered terminal-based todo/note manager

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc doc README.md etc/DATABASE_FORMAT.md etc/FUTURE.md etc/PERFORMANCE.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
